/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const STANDARDS = {
  LIGHTING: {
    INITIAL_VA: 100,
    INITIAL_AREA: 6,
    STEP_VA: 60,
    STEP_AREA: 4,
  },
  TUG: {
    KITCHEN_PERIMETER_STEP: 3.5,
    SOCIAL_PERIMETER_STEP: 5,
    MIN_VA_KITCHEN_FIRST_3: 600,
    MIN_VA_KITCHEN_OTHERS: 100,
    MIN_VA_SOCIAL: 100,
  },
  CABLES: {
    LIGHTING_BITOLA: 1.5,
    TUG_BITOLA: 2.5,
  }
};

export const ROOM_TYPES = [
  { value: 'living', label: 'Sala', icon: 'Sofa' },
  { value: 'bedroom', label: 'Quarto', icon: 'Bed' },
  { value: 'kitchen', label: 'Cozinha', icon: 'Utensils' },
  { value: 'bathroom', label: 'Banheiro', icon: 'Bath' },
  { value: 'laundry', label: 'Lavanderia', icon: 'WashingMachine' },
  { value: 'hallway', label: 'Corredor/Hall', icon: 'ChevronRight' },
  { value: 'other', label: 'Outro', icon: 'Layout' },
];

export const DEFAULT_CATALOG: Record<string, number> = {
  // Condutores
  'cable-1.5': 2.50,
  'cable-2.5': 3.80,
  'cable-4.0': 5.50,
  'cable-6.0': 8.50,
  'cable-10.0': 13.00,
  'cable-16.0': 21.00,
  
  // Infraestrutura e Quadros
  'conduit-20': 3.50,
  'conduit-25': 4.20,
  'box-4x2': 1.20,
  'box-4x4': 2.80,
  'box-octo': 2.50,
  'quadro-12': 85.00,
  'quadro-24': 145.00,
  
  // Proteção
  'breaker-10': 15.0,
  'breaker-16': 15.0,
  'breaker-20': 15.0,
  'breaker-32': 18.0,
  'breaker-40': 22.0,
  'breaker-50': 28.0,
  'dr-40a': 125.00,
  'dps-20ka': 65.00,
  'busbar-pente': 45.00,
  'busbar-neutro': 12.00,
  'busbar-terra': 12.00,
  
  // Entrada de Serviço (Padrão Copel Aéreo)
  'poste-concreto-8m': 650.00,
  'caixa-copel': 450.00,
  'caixa-copel-bifasica': 310.00,
  'caixa-copel-monofasica': 225.00,
  'caixa-copel-trifasica': 450.00,
  'caixa-copel-monofasica-sub': 300.00,
  'caixa-copel-trifasica-sub': 550.00,
  'caixa-passagem-copel': 275.00,
  'breaker-tripolar-50': 120.00,
  'breaker-tripolar-63': 150.00,
  'breaker-tripolar-80': 180.00,
  'breaker-tripolar-100': 220.00,
  'breaker-bipolar-50': 65.00,
  'breaker-bipolar-63': 75.00,
  'breaker-bipolar-70': 95.00,
  'breaker-monopolar-30': 40.00,
  'breaker-monopolar-40': 45.00,
  'breaker-monopolar-50': 50.00,
  'breaker-bipolar-40': 60.00,
  'cabo-multiplex-25': 16.00,
  'cabo-multiplex-3x25': 14.00,
  'cabo-multiplex-3x16': 12.00,
  'cabo-multiplex-3x35': 22.50,
  'cabo-multiplex-4x25': 16.00,
  'cabo-multiplex-4x35': 22.50,
  'cabo-multiplex-4x50': 35.00,
  'cabo-multiplex-2x10': 7.50,
  'cabo-multiplex-2x16': 10.00,
  'cabo-cobre-10': 22.50,
  'cabo-cobre-16': 65.00,
  'cabo-cobre-25': 90.00,
  'cabo-cobre-35': 120.00,
  'cabo-cobre-50': 170.00,
  'haste-copel-2.4': 40.00,
  'cabo-aterro-16': 11.50,
  'cabo-aterro-10': 9.00,
  'conector-grampo-u': 20.00,
  'eletroduto-pvc-rigid-2': 42.50,
  'eletroduto-pvc-rigid-1.5': 35.00,
  'curva-pvc-90-2': 17.50,
  'luva-eletroduto-2': 10.00,
  'luva-eletroduto-1.5': 8.00,
  'curva-pvc-longa-1.5': 25.00,
  'curva-pvc-longa-2': 35.00,
  'bucha-arruela-kit': 10.00,
  'parafuso-bucha-kit': 3.50,
  'abracadeira-tipo-d': 3.50,
  'roldana-isolador': 20.00,
  'parafuso-olhal': 27.50,
  'conector-ipc': 27.50,
  'conector-emenda': 20.00,
  'cordoalha-aco': 17.50,
  'tampa-reforcada': 140.00,
  'areia-media': 85.00,
  'fita-advertencia': 35.00,
  
  // Dispositivos
  'socket-10a': 14.00,
  'socket-20a': 18.00,
  'switch-simple': 12.00,
  'switch-3way': 18.00,
  'lamp-led-9w': 10.00,
  'soquete-e27': 5.00,
  'plafon-led': 35.00,
  
  // Carga Pesada
  'chuveiro-7500w': 160.00,
  'torneira-eletrica': 180.00,
  
  // Miudezas
  'fita-isolante': 8.00,
  'fita-autofusao': 25.00,
  'bucha-parafuso': 0.50,
};

export const CATALOG_NAMES: Record<string, string> = {
  // Condutores
  'cable-1.5': 'Cabo Flexível 1.5mm²',
  'cable-2.5': 'Cabo Flexível 2.5mm²',
  'cable-4.0': 'Cabo Flexível 4.0mm²',
  'cable-6.0': 'Cabo Flexível 6.0mm²',
  'cable-10.0': 'Cabo Flexível 10.0mm²',
  'cable-16.0': 'Cabo Flexível 16.0mm²',
  
  // Infraestrutura e Quadros
  'conduit-20': 'Eletroduto Flexível 20mm (3/4")',
  'conduit-25': 'Eletroduto Flexível 25mm (1")',
  'box-4x2': 'Caixa de Passagem 4x2',
  'box-4x4': 'Caixa de Passagem 4x4',
  'box-octo': 'Caixa Octogonal de Teto',
  'quadro-12': 'Quadro de Distribuição (12 disjuntores)',
  'quadro-24': 'Quadro de Distribuição (24 disjuntores)',
  
  // Proteção
  'breaker-10': 'Disjuntor Termomagnético 10A',
  'breaker-16': 'Disjuntor Termomagnético 16A',
  'breaker-20': 'Disjuntor Termomagnético 20A',
  'breaker-32': 'Disjuntor Termomagnético 32A',
  'breaker-40': 'Disjuntor Termomagnético 40A',
  'breaker-50': 'Disjuntor Termomagnético 50A',
  'dr-40a': 'Dispositivo DR 40A 30mA (Geral)',
  'dps-20ka': 'Dispositivo DPS 20kA',
  'busbar-pente': 'Barramento Pente Bifásico',
  'busbar-neutro': 'Barramento Neutro',
  'busbar-terra': 'Barramento Terra',
  
  // Entrada de Serviço
  'poste-concreto-8m': 'Poste de Concreto 7 a 9m',
  'caixa-copel': 'Caixa de Medição Padrão Copel',
  'caixa-copel-bifasica': 'Caixa de Medição Bifásica Copel',
  'caixa-copel-monofasica': 'Caixa de Medição Monofásica Copel',
  'caixa-copel-trifasica': 'Caixa de Medição Trifásica Copel',
  'caixa-copel-monofasica-sub': 'Caixa Monofásica Subterrânea',
  'caixa-copel-trifasica-sub': 'Caixa Trifásica Subterrânea',
  'caixa-passagem-copel': 'Caixa de Passagem Padrão Copel',
  'breaker-tripolar-50': 'Disjuntor Tripolar 50A',
  'breaker-tripolar-63': 'Disjuntor Tripolar 63A',
  'breaker-tripolar-80': 'Disjuntor Tripolar 80A',
  'breaker-tripolar-100': 'Disjuntor Tripolar 100A',
  'breaker-bipolar-50': 'Disjuntor Bipolar 50A',
  'breaker-bipolar-63': 'Disjuntor Bipolar 63A',
  'breaker-bipolar-70': 'Disjuntor Bipolar 70A',
  'breaker-monopolar-30': 'Disjuntor Monopolar 30A',
  'breaker-monopolar-40': 'Disjuntor Monopolar 40A',
  'breaker-monopolar-50': 'Disjuntor Monopolar 50A',
  'breaker-bipolar-40': 'Disjuntor Bipolar 40A',
  'cabo-multiplex-25': 'Cabo Multiplexado Alumínio 25mm²',
  'cabo-multiplex-3x25': 'Cabo Multiplexado Alumínio 3x25mm²',
  'cabo-multiplex-3x16': 'Cabo Multiplexado Alumínio 3x16mm²',
  'cabo-multiplex-3x35': 'Cabo Multiplexado Alumínio 3x35mm²',
  'cabo-multiplex-4x25': 'Cabo Multiplexado Alumínio 4x25mm²',
  'cabo-multiplex-4x35': 'Cabo Multiplexado Alumínio 4x35mm²',
  'cabo-multiplex-4x50': 'Cabo Multiplexado Alumínio 4x50mm²',
  'cabo-multiplex-2x10': 'Cabo Multiplexado Alumínio 2x10mm²',
  'cabo-multiplex-2x16': 'Cabo Multiplexado Alumínio 2x16mm²',
  'cabo-cobre-10': 'Cabo Cobre 10mm²',
  'cabo-cobre-16': 'Cabo Cobre 16mm²',
  'cabo-cobre-25': 'Cabo Cobre 25mm²',
  'cabo-cobre-35': 'Cabo Cobre 35mm²',
  'cabo-cobre-50': 'Cabo Cobre 50mm²',
  'haste-copel-2.4': 'Haste de Aterramento 2,4m',
  'cabo-aterro-16': 'Cabo Verde 16mm² (Terra)',
  'cabo-aterro-10': 'Cabo Verde 10mm² (Terra)',
  'conector-grampo-u': 'Conector de Aterramento (Grampo)',
  'eletroduto-pvc-rigid-2': 'Eletroduto PVC Rígido 2"',
  'eletroduto-pvc-rigid-1.5': 'Eletroduto PVC Rígido 1 1/2"',
  'curva-pvc-90-2': 'Curva 90° 2"',
  'luva-eletroduto-2': 'Luva Eletroduto 2"',
  'luva-eletroduto-1.5': 'Luva Eletroduto 1.5"',
  'curva-pvc-longa-1.5': 'Curva PVC Longa 1.5"',
  'curva-pvc-longa-2': 'Curva PVC Longa 2"',
  'bucha-arruela-kit': 'Kit Bucha + Arruela',
  'parafuso-bucha-kit': 'Kit Parafuso + Bucha',
  'abracadeira-tipo-d': 'Abraçadeira Tipo D',
  'roldana-isolador': 'Roldana / Isolador',
  'parafuso-olhal': 'Parafuso Olhal',
  'conector-ipc': 'Conector Perfurante (IPC)',
  'conector-emenda': 'Conector de Emenda',
  'cordoalha-aco': 'Cordoalha de Aço',
  'tampa-reforcada': 'Tampa Reforçada (Caixa Passagem)',
  'areia-media': 'Areia Média',
  'fita-advertencia': 'Fita de Advertência Elétrica',
  
  // Dispositivos
  'socket-10a': 'Tomada 2P+T 10A (TUG)',
  'socket-20a': 'Tomada 2P+T 20A (TUE)',
  'switch-simple': 'Interruptor Simples',
  'switch-3way': 'Interruptor Paralelo (Three-Way)',
  'lamp-led-9w': 'Lâmpada LED 9W',
  'soquete-e27': 'Soquete E27',
  'plafon-led': 'Plafon LED',
  
  // Carga Pesada
  'chuveiro-7500w': 'Chuveiro Elétrico 7500W',
  'torneira-eletrica': 'Torneira Elétrica',
  
  // Miudezas
  'fita-isolante': 'Fita Isolante',
  'fita-autofusao': 'Fita Autofusão',
  'bucha-parafuso': 'Bucha com Parafuso',
};
